### ISSUE TITLE
Errors related to `/tmp` folder inside Docker container. Why use of `Tempfile`?

### ISSUE THREAD

**Issue by bitcrumb** [beplus/fastlane-plugin-versioning_android#19]
I am being faced with the following error when running a Fastlane lane in a Docker container (based on `debian:bullseye-slim`):

```
/usr/lib/ruby/2.7.0/fileutils.rb:548:in `rename': Invalid cross-device link @ rb_file_s_rename - (/tmp/fastlaneIncrementVersionName20230307-13093-1g2hon7, ./android/app/build.gradle) (Errno::EXDEV)

/usr/lib/ruby/2.7.0/fileutils.rb:1424:in `utime': \e[31m[!] Operation not permitted @ apply2files - ./android/app/build.gradle\e[0m (Errno::EPERM)
```

Any specific reason this plugin uses a temporary file in the `/tmp` folder for making changes to the `build.gradle` instead of replacing directly in the original `build.gradle` file?

This seems like an unnecessary detour?

**Comment by bitcrumb** [comment]
I think the issue is that you can't move files over different mounts, so it would probably work if the file was copied & removed instead (or no Tempfile was used at all).
